//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.269
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GvoHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GvoHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _00000001 {
            get {
                object obj = ResourceManager.GetObject("_00000001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000005 {
            get {
                object obj = ResourceManager.GetObject("_00000005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000010 {
            get {
                object obj = ResourceManager.GetObject("_00000010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000011 {
            get {
                object obj = ResourceManager.GetObject("_00000011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000012 {
            get {
                object obj = ResourceManager.GetObject("_00000012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000016 {
            get {
                object obj = ResourceManager.GetObject("_00000016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000017 {
            get {
                object obj = ResourceManager.GetObject("_00000017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000018 {
            get {
                object obj = ResourceManager.GetObject("_00000018", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000019 {
            get {
                object obj = ResourceManager.GetObject("_00000019", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000020 {
            get {
                object obj = ResourceManager.GetObject("_00000020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000022 {
            get {
                object obj = ResourceManager.GetObject("_00000022", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000031 {
            get {
                object obj = ResourceManager.GetObject("_00000031", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000032 {
            get {
                object obj = ResourceManager.GetObject("_00000032", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000034 {
            get {
                object obj = ResourceManager.GetObject("_00000034", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000035 {
            get {
                object obj = ResourceManager.GetObject("_00000035", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000036 {
            get {
                object obj = ResourceManager.GetObject("_00000036", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000037 {
            get {
                object obj = ResourceManager.GetObject("_00000037", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000042 {
            get {
                object obj = ResourceManager.GetObject("_00000042", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000043 {
            get {
                object obj = ResourceManager.GetObject("_00000043", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000044 {
            get {
                object obj = ResourceManager.GetObject("_00000044", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000045 {
            get {
                object obj = ResourceManager.GetObject("_00000045", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000072 {
            get {
                object obj = ResourceManager.GetObject("_00000072", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000073 {
            get {
                object obj = ResourceManager.GetObject("_00000073", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000074 {
            get {
                object obj = ResourceManager.GetObject("_00000074", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000075 {
            get {
                object obj = ResourceManager.GetObject("_00000075", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000076 {
            get {
                object obj = ResourceManager.GetObject("_00000076", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000077 {
            get {
                object obj = ResourceManager.GetObject("_00000077", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000078 {
            get {
                object obj = ResourceManager.GetObject("_00000078", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000080 {
            get {
                object obj = ResourceManager.GetObject("_00000080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000081 {
            get {
                object obj = ResourceManager.GetObject("_00000081", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000082 {
            get {
                object obj = ResourceManager.GetObject("_00000082", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000102 {
            get {
                object obj = ResourceManager.GetObject("_00000102", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000103 {
            get {
                object obj = ResourceManager.GetObject("_00000103", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000107 {
            get {
                object obj = ResourceManager.GetObject("_00000107", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000109 {
            get {
                object obj = ResourceManager.GetObject("_00000109", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000111 {
            get {
                object obj = ResourceManager.GetObject("_00000111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000114 {
            get {
                object obj = ResourceManager.GetObject("_00000114", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000115 {
            get {
                object obj = ResourceManager.GetObject("_00000115", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000116 {
            get {
                object obj = ResourceManager.GetObject("_00000116", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000117 {
            get {
                object obj = ResourceManager.GetObject("_00000117", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000118 {
            get {
                object obj = ResourceManager.GetObject("_00000118", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000120 {
            get {
                object obj = ResourceManager.GetObject("_00000120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000121 {
            get {
                object obj = ResourceManager.GetObject("_00000121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000123 {
            get {
                object obj = ResourceManager.GetObject("_00000123", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000125 {
            get {
                object obj = ResourceManager.GetObject("_00000125", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000126 {
            get {
                object obj = ResourceManager.GetObject("_00000126", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000128 {
            get {
                object obj = ResourceManager.GetObject("_00000128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000130 {
            get {
                object obj = ResourceManager.GetObject("_00000130", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000131 {
            get {
                object obj = ResourceManager.GetObject("_00000131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000132 {
            get {
                object obj = ResourceManager.GetObject("_00000132", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000133 {
            get {
                object obj = ResourceManager.GetObject("_00000133", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000134 {
            get {
                object obj = ResourceManager.GetObject("_00000134", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000135 {
            get {
                object obj = ResourceManager.GetObject("_00000135", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000250 {
            get {
                object obj = ResourceManager.GetObject("_00000250", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000260 {
            get {
                object obj = ResourceManager.GetObject("_00000260", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000261 {
            get {
                object obj = ResourceManager.GetObject("_00000261", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000262 {
            get {
                object obj = ResourceManager.GetObject("_00000262", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000263 {
            get {
                object obj = ResourceManager.GetObject("_00000263", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000280 {
            get {
                object obj = ResourceManager.GetObject("_00000280", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000281 {
            get {
                object obj = ResourceManager.GetObject("_00000281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000282 {
            get {
                object obj = ResourceManager.GetObject("_00000282", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000283 {
            get {
                object obj = ResourceManager.GetObject("_00000283", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000284 {
            get {
                object obj = ResourceManager.GetObject("_00000284", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000285 {
            get {
                object obj = ResourceManager.GetObject("_00000285", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000286 {
            get {
                object obj = ResourceManager.GetObject("_00000286", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000287 {
            get {
                object obj = ResourceManager.GetObject("_00000287", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000288 {
            get {
                object obj = ResourceManager.GetObject("_00000288", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000289 {
            get {
                object obj = ResourceManager.GetObject("_00000289", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000290 {
            get {
                object obj = ResourceManager.GetObject("_00000290", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000291 {
            get {
                object obj = ResourceManager.GetObject("_00000291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000375 {
            get {
                object obj = ResourceManager.GetObject("_00000375", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000376 {
            get {
                object obj = ResourceManager.GetObject("_00000376", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000507 {
            get {
                object obj = ResourceManager.GetObject("_00000507", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000530 {
            get {
                object obj = ResourceManager.GetObject("_00000530", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000531 {
            get {
                object obj = ResourceManager.GetObject("_00000531", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000532 {
            get {
                object obj = ResourceManager.GetObject("_00000532", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000533 {
            get {
                object obj = ResourceManager.GetObject("_00000533", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000534 {
            get {
                object obj = ResourceManager.GetObject("_00000534", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000535 {
            get {
                object obj = ResourceManager.GetObject("_00000535", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000536 {
            get {
                object obj = ResourceManager.GetObject("_00000536", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000600 {
            get {
                object obj = ResourceManager.GetObject("_00000600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000601 {
            get {
                object obj = ResourceManager.GetObject("_00000601", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000602 {
            get {
                object obj = ResourceManager.GetObject("_00000602", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000603 {
            get {
                object obj = ResourceManager.GetObject("_00000603", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000610 {
            get {
                object obj = ResourceManager.GetObject("_00000610", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000706 {
            get {
                object obj = ResourceManager.GetObject("_00000706", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000707 {
            get {
                object obj = ResourceManager.GetObject("_00000707", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000709 {
            get {
                object obj = ResourceManager.GetObject("_00000709", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000710 {
            get {
                object obj = ResourceManager.GetObject("_00000710", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000711 {
            get {
                object obj = ResourceManager.GetObject("_00000711", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000713 {
            get {
                object obj = ResourceManager.GetObject("_00000713", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000714 {
            get {
                object obj = ResourceManager.GetObject("_00000714", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000715 {
            get {
                object obj = ResourceManager.GetObject("_00000715", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000717 {
            get {
                object obj = ResourceManager.GetObject("_00000717", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000719 {
            get {
                object obj = ResourceManager.GetObject("_00000719", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000721 {
            get {
                object obj = ResourceManager.GetObject("_00000721", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000723 {
            get {
                object obj = ResourceManager.GetObject("_00000723", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000724 {
            get {
                object obj = ResourceManager.GetObject("_00000724", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000725 {
            get {
                object obj = ResourceManager.GetObject("_00000725", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000728 {
            get {
                object obj = ResourceManager.GetObject("_00000728", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000729 {
            get {
                object obj = ResourceManager.GetObject("_00000729", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000730 {
            get {
                object obj = ResourceManager.GetObject("_00000730", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000732 {
            get {
                object obj = ResourceManager.GetObject("_00000732", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000741 {
            get {
                object obj = ResourceManager.GetObject("_00000741", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000742 {
            get {
                object obj = ResourceManager.GetObject("_00000742", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000743 {
            get {
                object obj = ResourceManager.GetObject("_00000743", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000754 {
            get {
                object obj = ResourceManager.GetObject("_00000754", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000759 {
            get {
                object obj = ResourceManager.GetObject("_00000759", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000951 {
            get {
                object obj = ResourceManager.GetObject("_00000951", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000952 {
            get {
                object obj = ResourceManager.GetObject("_00000952", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000953 {
            get {
                object obj = ResourceManager.GetObject("_00000953", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000954 {
            get {
                object obj = ResourceManager.GetObject("_00000954", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000955 {
            get {
                object obj = ResourceManager.GetObject("_00000955", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000956 {
            get {
                object obj = ResourceManager.GetObject("_00000956", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000957 {
            get {
                object obj = ResourceManager.GetObject("_00000957", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000958 {
            get {
                object obj = ResourceManager.GetObject("_00000958", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000959 {
            get {
                object obj = ResourceManager.GetObject("_00000959", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000960 {
            get {
                object obj = ResourceManager.GetObject("_00000960", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000961 {
            get {
                object obj = ResourceManager.GetObject("_00000961", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000962 {
            get {
                object obj = ResourceManager.GetObject("_00000962", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000963 {
            get {
                object obj = ResourceManager.GetObject("_00000963", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000964 {
            get {
                object obj = ResourceManager.GetObject("_00000964", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000965 {
            get {
                object obj = ResourceManager.GetObject("_00000965", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000966 {
            get {
                object obj = ResourceManager.GetObject("_00000966", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000967 {
            get {
                object obj = ResourceManager.GetObject("_00000967", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000968 {
            get {
                object obj = ResourceManager.GetObject("_00000968", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000969 {
            get {
                object obj = ResourceManager.GetObject("_00000969", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00000970 {
            get {
                object obj = ResourceManager.GetObject("_00000970", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00001200 {
            get {
                object obj = ResourceManager.GetObject("_00001200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00001201 {
            get {
                object obj = ResourceManager.GetObject("_00001201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00001210 {
            get {
                object obj = ResourceManager.GetObject("_00001210", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00001211 {
            get {
                object obj = ResourceManager.GetObject("_00001211", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00001212 {
            get {
                object obj = ResourceManager.GetObject("_00001212", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00001213 {
            get {
                object obj = ResourceManager.GetObject("_00001213", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00001214 {
            get {
                object obj = ResourceManager.GetObject("_00001214", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00001215 {
            get {
                object obj = ResourceManager.GetObject("_00001215", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00001216 {
            get {
                object obj = ResourceManager.GetObject("_00001216", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00001500 {
            get {
                object obj = ResourceManager.GetObject("_00001500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00001501 {
            get {
                object obj = ResourceManager.GetObject("_00001501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00001502 {
            get {
                object obj = ResourceManager.GetObject("_00001502", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002000 {
            get {
                object obj = ResourceManager.GetObject("_00002000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002001 {
            get {
                object obj = ResourceManager.GetObject("_00002001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002003 {
            get {
                object obj = ResourceManager.GetObject("_00002003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002004 {
            get {
                object obj = ResourceManager.GetObject("_00002004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002005 {
            get {
                object obj = ResourceManager.GetObject("_00002005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002011 {
            get {
                object obj = ResourceManager.GetObject("_00002011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002020 {
            get {
                object obj = ResourceManager.GetObject("_00002020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002040 {
            get {
                object obj = ResourceManager.GetObject("_00002040", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002041 {
            get {
                object obj = ResourceManager.GetObject("_00002041", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002043 {
            get {
                object obj = ResourceManager.GetObject("_00002043", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002060 {
            get {
                object obj = ResourceManager.GetObject("_00002060", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002061 {
            get {
                object obj = ResourceManager.GetObject("_00002061", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002062 {
            get {
                object obj = ResourceManager.GetObject("_00002062", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002063 {
            get {
                object obj = ResourceManager.GetObject("_00002063", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002081 {
            get {
                object obj = ResourceManager.GetObject("_00002081", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002083 {
            get {
                object obj = ResourceManager.GetObject("_00002083", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002105 {
            get {
                object obj = ResourceManager.GetObject("_00002105", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002106 {
            get {
                object obj = ResourceManager.GetObject("_00002106", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002121 {
            get {
                object obj = ResourceManager.GetObject("_00002121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002124 {
            get {
                object obj = ResourceManager.GetObject("_00002124", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002125 {
            get {
                object obj = ResourceManager.GetObject("_00002125", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002500 {
            get {
                object obj = ResourceManager.GetObject("_00002500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002729 {
            get {
                object obj = ResourceManager.GetObject("_00002729", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002796 {
            get {
                object obj = ResourceManager.GetObject("_00002796", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002797 {
            get {
                object obj = ResourceManager.GetObject("_00002797", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00002798 {
            get {
                object obj = ResourceManager.GetObject("_00002798", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _0001 {
            get {
                object obj = ResourceManager.GetObject("_0001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _0002 {
            get {
                object obj = ResourceManager.GetObject("_0002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _0003 {
            get {
                object obj = ResourceManager.GetObject("_0003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01400100 {
            get {
                object obj = ResourceManager.GetObject("_01400100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01400200 {
            get {
                object obj = ResourceManager.GetObject("_01400200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01400300 {
            get {
                object obj = ResourceManager.GetObject("_01400300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01400400 {
            get {
                object obj = ResourceManager.GetObject("_01400400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500013 {
            get {
                object obj = ResourceManager.GetObject("_01500013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500015 {
            get {
                object obj = ResourceManager.GetObject("_01500015", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500016 {
            get {
                object obj = ResourceManager.GetObject("_01500016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500022 {
            get {
                object obj = ResourceManager.GetObject("_01500022", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500023 {
            get {
                object obj = ResourceManager.GetObject("_01500023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500024 {
            get {
                object obj = ResourceManager.GetObject("_01500024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500026 {
            get {
                object obj = ResourceManager.GetObject("_01500026", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500049 {
            get {
                object obj = ResourceManager.GetObject("_01500049", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500054 {
            get {
                object obj = ResourceManager.GetObject("_01500054", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500055 {
            get {
                object obj = ResourceManager.GetObject("_01500055", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500057 {
            get {
                object obj = ResourceManager.GetObject("_01500057", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500058 {
            get {
                object obj = ResourceManager.GetObject("_01500058", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500059 {
            get {
                object obj = ResourceManager.GetObject("_01500059", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500060 {
            get {
                object obj = ResourceManager.GetObject("_01500060", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500068 {
            get {
                object obj = ResourceManager.GetObject("_01500068", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500069 {
            get {
                object obj = ResourceManager.GetObject("_01500069", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500070 {
            get {
                object obj = ResourceManager.GetObject("_01500070", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500071 {
            get {
                object obj = ResourceManager.GetObject("_01500071", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500073 {
            get {
                object obj = ResourceManager.GetObject("_01500073", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500074 {
            get {
                object obj = ResourceManager.GetObject("_01500074", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500075 {
            get {
                object obj = ResourceManager.GetObject("_01500075", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500077 {
            get {
                object obj = ResourceManager.GetObject("_01500077", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500100 {
            get {
                object obj = ResourceManager.GetObject("_01500100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500104 {
            get {
                object obj = ResourceManager.GetObject("_01500104", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500131 {
            get {
                object obj = ResourceManager.GetObject("_01500131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500132 {
            get {
                object obj = ResourceManager.GetObject("_01500132", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500133 {
            get {
                object obj = ResourceManager.GetObject("_01500133", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500134 {
            get {
                object obj = ResourceManager.GetObject("_01500134", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500135 {
            get {
                object obj = ResourceManager.GetObject("_01500135", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500136 {
            get {
                object obj = ResourceManager.GetObject("_01500136", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500137 {
            get {
                object obj = ResourceManager.GetObject("_01500137", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500138 {
            get {
                object obj = ResourceManager.GetObject("_01500138", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500139 {
            get {
                object obj = ResourceManager.GetObject("_01500139", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500140 {
            get {
                object obj = ResourceManager.GetObject("_01500140", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500142 {
            get {
                object obj = ResourceManager.GetObject("_01500142", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500143 {
            get {
                object obj = ResourceManager.GetObject("_01500143", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500144 {
            get {
                object obj = ResourceManager.GetObject("_01500144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500145 {
            get {
                object obj = ResourceManager.GetObject("_01500145", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500146 {
            get {
                object obj = ResourceManager.GetObject("_01500146", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500147 {
            get {
                object obj = ResourceManager.GetObject("_01500147", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500148 {
            get {
                object obj = ResourceManager.GetObject("_01500148", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500149 {
            get {
                object obj = ResourceManager.GetObject("_01500149", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500155 {
            get {
                object obj = ResourceManager.GetObject("_01500155", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500156 {
            get {
                object obj = ResourceManager.GetObject("_01500156", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500186 {
            get {
                object obj = ResourceManager.GetObject("_01500186", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500187 {
            get {
                object obj = ResourceManager.GetObject("_01500187", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500188 {
            get {
                object obj = ResourceManager.GetObject("_01500188", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500189 {
            get {
                object obj = ResourceManager.GetObject("_01500189", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500190 {
            get {
                object obj = ResourceManager.GetObject("_01500190", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500191 {
            get {
                object obj = ResourceManager.GetObject("_01500191", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500192 {
            get {
                object obj = ResourceManager.GetObject("_01500192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500242 {
            get {
                object obj = ResourceManager.GetObject("_01500242", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500243 {
            get {
                object obj = ResourceManager.GetObject("_01500243", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500244 {
            get {
                object obj = ResourceManager.GetObject("_01500244", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500245 {
            get {
                object obj = ResourceManager.GetObject("_01500245", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500246 {
            get {
                object obj = ResourceManager.GetObject("_01500246", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500247 {
            get {
                object obj = ResourceManager.GetObject("_01500247", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500456 {
            get {
                object obj = ResourceManager.GetObject("_01500456", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500460 {
            get {
                object obj = ResourceManager.GetObject("_01500460", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500463 {
            get {
                object obj = ResourceManager.GetObject("_01500463", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500465 {
            get {
                object obj = ResourceManager.GetObject("_01500465", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500471 {
            get {
                object obj = ResourceManager.GetObject("_01500471", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500482 {
            get {
                object obj = ResourceManager.GetObject("_01500482", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500483 {
            get {
                object obj = ResourceManager.GetObject("_01500483", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500484 {
            get {
                object obj = ResourceManager.GetObject("_01500484", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500485 {
            get {
                object obj = ResourceManager.GetObject("_01500485", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01500523 {
            get {
                object obj = ResourceManager.GetObject("_01500523", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 [City]
        ///塞維爾        =15904,3261
        ///里斯本        =15794,3204
        ///威尼斯        =  537,2800
        ///馬賽          =  128,2962
        ///阿姆斯特丹    =   96,2506
        ///倫敦          =16324,2410
        ///奧波多        =15774,3118
        ///馬拉加        =16050,3270
        ///瓦倫西亞      =16170,3154
        ///巴賽隆納      =16358,3102
        ///帕爾馬        =16294,3214
        ///休達          =15962,3366
        ///阿爾及爾      =   40,3280
        ///波爾多        =16116,2832
        ///南特          =16104,2736
        ///安特衛普      =   50,2530
        ///漢堡          =  356,2372
        ///加來          =16312,2568
        ///奧斯陸        =  494,1946
        ///卑爾根        =  244,1956
        ///都柏林        =16040,2280
        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Coordinate {
            get {
                return ResourceManager.GetString("Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1505000=香草醬汁泡蝦
        ///1505001=沙司牛排
        ///1505002=焗烤艾登乳酪
        ///1505003=炸魚
        ///1505004=馬賽魚湯
        ///1505005=西班牙雞肉飯
        ///1505006=海鮮披薩
        ///1505007=希臘肉末茄盒
        ///1505008=土耳其烤牛肉
        ///1505009=夏南瓜包肉
        ///1505010=非洲庫斯庫斯
        ///1505011=香瓜籽湯
        ///1505012=酥炸沙摩水餃
        ///1505013=阿拉伯飯
        ///1505014=乾菜扣羊肉
        ///1505015=蔬菜咖哩
        ///1505016=羊肉咖哩
        ///1505017=烤肉夾木瓜膜
        ///1505018=臘肉豆湯
        ///1505019=蠶豆湯
        ///1505020=蒜乳酪
        ///1505021=水煮蛋
        ///1505022=羅勒義大利麵
        ///1505023=醃肉麥片粥
        ///1505024=燻製鯡魚
        ///1505025=乳酪味煎火腿
        ///1505026=奶油嫩煎蘑菇
        ///1505027=乳酪蛋捲
        ///1505028=海鮮義大利麵
        ///1505029=蘑菇義大利麵
        ///1505030=烤雞肉
        ///1505031=葡萄酒蒸鱈魚
        ///1505032=法式黃油烤鮭魚
        ///1505033=烤海鮮
        ///1505034=香 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Cuisine {
            get {
                return ResourceManager.GetString("Cuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7=鰹魚加工
        ///33=葛布蘭織錦製法
        ///34=錦緞製法
        ///35=喬其紗製法
        ///36=塔夫綢製法
        ///37=英格蘭花呢製法
        ///39=法蘭絨製法
        ///40=天鵝絨製法
        ///41=平紋薄呢製法
        ///42=蕾絲花邊製法
        ///43=高級服飾製法
        ///60=鐵材製法
        ///61=鋼的製法
        ///62=銅的製法
        ///63=鉛的製法
        ///153=乳酪的焗烤料理
        ///154=炸魚
        ///155=番紅花燉海鮮
        ///156=西班牙雞肉飯
        ///157=海鮮披薩
        ///158=希臘風味的千層燒
        ///159=土耳其牛肉料理
        ///160=小亞細亞的填餡料理
        ///168=木瓜的填餡料理
        ///171=大蒜和乳酪的料理
        ///172=簡單的蛋類料理
        ///176=乳酪味煎火腿
        ///177=簡易嫩煎蘑菇
        ///178=乳酪和蛋的料理
        ///184=烤海鮮
        ///187=清蒸比目魚
        ///188=乳酪烤鯛魚
        ///194=鮪魚排
        ///215=義大利的甜麵包
        ///216=樹墩形狀的烤點心
        ///217=鬆軟的烤點心
        ///218=使用乳酪的蛋糕
        ///232=製粉法
        ///236=香料束的製法
        ///237=清湯的秘訣
        ///253=鮪魚加工
        ///254=鯖魚加工
        ///255=鯡魚加工
        ///256=沙丁魚加工
        ///257=秋刀魚加工
        ///258=鱈魚加工
        ///25 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [採買書]
        ///1500228=進貨採買書（類別1）
        ///1500229=進貨採買書（類別2）
        ///1500230=進貨採買書（類別3）
        ///1500231=進貨採買書（類別4）
        ///[消災]
        ///1500002=救生工具
        ///1500007=滅火砂
        ///1500011=水桶
        ///1500012=萊姆果汁
        ///1500020=滅鼠藥
        ///1500021=消愁酒桶
        ///1500033=沉靜的旗幟
        ///1500035=神秘的羽扇
        ///1500036=疾病用特效藥
        ///1500041=純綿的耳塞
        ///1500042=備用船帆
        ///1500043=備用船舵
        ///1500044=名匠工具
        ///1500072=懲罰的繩索
        ///1500079=防海魔的聖痕
        ///1500080=防大章魚的聖痕
        ///1500081=防大鯊魚的聖痕
        ///1500108=清潔用甲板長刷
        ///1500109=安眠吊床
        ///1500151=望鄉排鐘
        ///1500152=船歌的樂譜
        ///1500050=停戰協定書
        ///1500254=高級上納品（大型船用）
        ///1500255=高級上納品（中型船用）
        ///1500256=高級上納品（小型船用）
        ///1500258=獻給地方海盜的上納品
        ///[陸戰]
        ///1500013 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [冒險]
        ///1=操帆
        ///5=測量
        ///6=地理學
        ///8=生存
        ///10=生態調查
        ///11=調度
        ///12=釣魚
        ///13=補給
        ///14=行軍
        ///16=視認
        ///17=採集
        ///18=救助
        ///19=驅除
        ///20=搜索
        ///22=開鎖
        ///25=考古學
        ///26=宗教學
        ///27=生物學
        ///28=美術
        ///29=財寶鑑定
        ///31=酒宴
        ///32=求愛
        ///34=發現水雷
        ///35=觀察
        ///36=吉他演奏
        ///37=笛子演奏
        ///38=手鼓演奏
        ///39=小提琴演奏
        ///40=投擲術
        ///41=航行技術
        ///42=語言學
        ///43=打撈船隻
        ///44=拖航
        ///45=陷阱
        ///[交易]
        ///50=會計
        ///51=食品買賣
        ///52=調味料買賣
        ///53=酒類買賣
        ///54=嗜好品買賣
        ///55=香辛料買賣
        ///56=醫藥品買賣
        ///57=纖維買賣
        ///58=紡織品買賣
        ///59=染料買賣
        ///60=貴金屬買賣
        ///61=礦石買賣
        ///62=香料買賣
        ///63=寶石買賣
        ///64=家畜買賣
        ///65=武器買賣
        ///66=火器買賣
        ///67=美術品買賣
        ///68=工藝品買賣
        ///69=工業製品買賣
        ///70=雜貨買賣
        ///72=烹飪
        ///73=縫紉
        ///74=鑄造
        ///75=警戒
        ///76=身體語言
        ///77=運用
        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Skill {
            get {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }
    }
}
